### ISSUE TITLE
Image Input Dialog

### ISSUE THREAD

**Issue by sportnak** [ckeditor/ckeditor-sdk#138]
When using the "add-image" button from the editor while the editor is in a dialog, any attempt to input information to the image dialog is simply put in the editor itself.

**Comment by Reinmar** [comment]
If you meant to report a bug, then please do so on http://dev.ckeditor.com, because this issue tracker covers only http://sdk.ckeditor.com.

You will, however, need to provide more information on how to reproduce it (and where – a sample is needed if it cannot be reproduced on some existing sample), on what browser and what are the steps required.
