### ISSUE TITLE
Table: Insert Column before and After fails if a cell vertical split exist

### ISSUE THREAD

**Issue by rinoreji** [ckeditor/ckeditor-sdk#164]
Create a table as shown below
![image](https://cloud.githubusercontent.com/assets/1198678/9654687/fae50902-5249-11e5-8592-c01d95aad33d.png)

Try to do a 'Insert column before' at the column4. Expected behaviour will be a column in between column3 and column4
but the actual result is a column created before column3
![image](https://cloud.githubusercontent.com/assets/1198678/9654786/87c5e5bc-524a-11e5-9d45-b6b63781eb5f.png)

**Comment by Reinmar** [comment]
Please report this issue on http://dev.ckeditor.com. This issue tracker is related to the http://sdk.ckeditor.com site and builder.

BTW. I can reply straight away that this issue is caused by browsers moving selection from one cell to another on right click if the cell is nearly empty. Put some content in these cells and it won't be reproducible. Of course, that's still an issue, but it's something tricky to workaround.

**Comment by rinoreji** [comment]
new ticket at dev.ckeditor - http://dev.ckeditor.com/ticket/13729
