### ISSUE TITLE
Unable to type anything in ckeditor after inserting image

### ISSUE THREAD

**Issue by venkatesh-innoppl** [ckeditor/ckeditor-sdk#178]
I have inserted an image and changed image alignment as left by using Image Properties dialogue box (opens when we double click an image). Again, if I open Image properties and check Captioned image option, I could not able to type anything after image. This happens especially in chrome browser.

Please find the steps to reproduce the issue in chrome browser:

    Insert an image using ckeditor image option.
    Double click on the image to open Image Properties dialogue box
    Set Alignment as left and click OK.
    Again open Image Properties dialogue box by double clicking image and check "Captioned image" checkbox. Click OK.
    Now, you will not be able to type anything after image.

**Comment by mlewand** [comment]
Could you provide some more information?

1. What is the URL of SDK sample that you're facing this problem (we have two image plugins)?
1. How do you attempt to type something after the image? There are miltiple ways, you could try to put cursor with a mouse click "after the image", or you could just left click image, and press right arrow on the keyboard to move the selection after it.

**Comment by venkatesh-innoppl** [comment]
Please find the below information:

1. URL - http://sdk.ckeditor.com/samples/captionedimage.html (please erase all the existing content in ckeditor and then insert an image)

I hope issue exists in both image and image 2 plugins

2.  I tried to put cursor with a mouse click "after the image"

**Comment by venkatesh-innoppl** [comment]
Let me know if you need anymore information to reproduce the issue in chrome

**Comment by mlewand** [comment]
Ok so this is an image2 issue, but it is not a problem of SDK itself but CKEditor4. I'll ask you to fill a proper issue in [CKEditor issue tracker](dev.ckeditor.com).

See our [Reporting Issues guide](http://docs.ckeditor.com/#!/guide/dev_issues_readme) for information on how to do it.

BTW. there's a big chance that this ticket is already reported there, if you find it, just add yourself to the cc list so that you are updated about changes in the ticket.
