### ISSUE TITLE
The link for "Samples" brings up nothing

### ISSUE THREAD

**Issue by AL-X-dev** [ckeditor/ckeditor-sdk#188]
On the following page:

    http://sdk.ckeditor.com/index.html

The link for "samples" has no effect.

**Comment by mlewand** [comment]
Thanks! @AnnaTomanek could you take a look on this?

**Comment by AnnaTomanek** [comment]
This is a bit of a UX problem - the link does not work because you actually *are* on the samples main page. The text description below explains that you need to choose a sample from the sidebar on the left to start.

We'll try to think about how to improve the UX here, perhaps by expanding the samples in the sidebar and/or modifying the text. Thanks for your feedback!
