### ISSUE TITLE
Showcase styling captioned images

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-sdk#192]
Here: http://sdk.ckeditor.com/samples/captionedimage.html and mention a link to http://docs.ckeditor.com/#!/guide/dev_styles-section-widget-styles

**Comment by AnnaTomanek** [comment]
Question is: should it be showcased in the captioned image sample (and be still invisible on samples for other widgets) or in the [Styles](http://sdk.ckeditor.com/samples/styles.html) sample, as a special case, with some more widgets?

We could then move [Olek's demo](http://ckeditor.com/tmp/4.4.0/widget-styles.html) there (because it's stupid to keep it on a separate temp page anyway). Or maybe add it as a separate sample to not make the Styles one longer?

**Comment by wwalc** [comment]
> Question is: should it (...) in the Styles sample, as a special case, with some more widgets?

That's a good idea, let's have it there.

Additionally, on each sample showcasing a widget let's have a "Related features" link to section about styling widgets. And on the captioned image sample let's define just some styles for the styles combo (actually, it may be not needed if https://dev.ckeditor.com/ticket/16644 is implemented).
