### ISSUE TITLE
Media Embed sample does not work

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor-sdk#213]
http://sdk.ckeditor.com/samples/mediaembed.html

Most likely due to changes in 4.7.

**Comment by mlewand** [comment]
Yes it is:
* http://docs.ckeditor.com/#!/guide/dev_media_embed-section-configuring-the-content-provider
* http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-embed_provider

Setting value back to `//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}` will do the deal, **but google maps** won't work AFAIK - that's because ifreamely no longer serves google maps for free tiers.

**Comment by mlewand** [comment]
so we should remove google map link
