### ISSUE TITLE
Unrestricted CKFinder File Upload

### ISSUE THREAD

**Issue by laggerghost** [ckeditor/ckeditor-sdk#283]
Author	    : L4663r666h05t
Proof       : http://archive.is/EkxDg
File Upload : https://sdk.ckeditor.com/ckfinder/ckfinder.html
For Files   : https://sdk.ckeditor.com/ckfinder/ckfinder.html?type=Files&CKEditor=editor1&CKEditorFuncNum=0&langCode=en
For Images  : https://sdk.ckeditor.com/ckfinder/ckfinder.html?type=Images&CKEditor=editor1&CKEditorFuncNum=0&langCode=en
Files POST to  : https://localhost/userfiles/files/ourfile.txt
Images POST to : https://localhost/userfiles/files/ourimgs.png | .jpg | .jpeg | etc.

Anyone can upload a file & You do not block the extension, maybe in future. 
Someone can upload backdoor with this file uploader. So i guess to close this file upload for public. 
And redirect if someone want to know the directory

How to Upload? Click Upload and Choose the file or image to upload that.

Like if i open https://localhost.com/userfiles/files/ will redirect to other page :)

Thanks to: T1KUS90T - ./Serizawa - KID2Z0N3 - Panjul Dot ID - Indonesian Hackers

**Comment by vokiel** [comment]
We allowed public write access to the CKFinder because we use it in the SDK demo (see [Default Image Plugin](https://sdk.ckeditor.com/samples/image.html)). Without such permissions you wouldn't be able to upload anything while testing the sample.

> You do not block the extension, maybe in future.

We do block uploads by extensions (to be specific we use white-list to allow only chosen ones). But `.txt`, `.png`, `.jpg`, `.jpeg` are not blocked because they are not a threat to the server. You can send backdoor in `backdoor.txt` and navigate to that file - but it won't be parsed by the server - just displayed as plain text in the browser.

Also, we can not block access to those files, if someone will type they full path in browser address bar, as this is the same way they are inserted into CKEditor sample.
